INSERT INTO `employee` VALUES ('00002', 'Hồ Sỹ Thắng', 'thangdeptrai@gmail.com');
INSERT INTO `employee` VALUES ('012', 'Chó văn Mèo :) ', 'chomeo@yahoo.com');
INSERT INTO `employee` VALUES ('0123', 'Trần Thị Ly', 'chonoc@gmail.com');
INSERT INTO `employee` VALUES ('10000', 'Tom', 'holoi@gmail.com');
INSERT INTO `employee` VALUES ('10001', 'Sam', 'sam@gmail.com');
INSERT INTO `employee` VALUES ('10002', 'David', 'david@gmail.com');
INSERT INTO `employee` VALUES ('10021', 'Hồ Sỹ Lợi', '10021');
INSERT INTO `employee` VALUES ('1003', 'Tim', 'tim@gmail.com');
INSERT INTO `employee` VALUES ('1004', 'Black', 'black@gmail.com');
INSERT INTO `employee` VALUES ('1005', 'Whote', 'white@yahoo.com');
INSERT INTO `employee` VALUES ('1006', 'yellow', 'yellow1474@yahoo.com');
INSERT INTO `employee` VALUES ('11111', 'Trần Thị Ly', 'lycookie@gmail.com');
INSERT INTO `employee` VALUES ('1212', 'Trần Thị Ly', 'hosyloi97@gmail.com');
INSERT INTO `employee` VALUES ('1212121', 'vũ thị thương thương', 'nevergiveup@gmail.com');
INSERT INTO `employee` VALUES ('1231', 'Trần Văn Công', 'congcong@gmail.com');
INSERT INTO `employee` VALUES ('12312', 'Agenla baby', 'bongdaclc@gmail.com');
INSERT INTO `employee` VALUES ('1234', 'Demo', '1234');
INSERT INTO `employee` VALUES ('12341', 'Hi', 'mrloiho97@gmail.com');
INSERT INTO `employee` VALUES ('123411', 'vũ thị thương thương', 'holoihalinh@gmail.com');
INSERT INTO `employee` VALUES ('123412', 'Lê Thị Nhung', 'mrloiho97@gmail.com');
INSERT INTO `employee` VALUES ('12342', 'Phan Thị Mèo', 'meomeomeo@gmail.com');
INSERT INTO `employee` VALUES ('12345', 'Hồ Sỹ Lợi', 'holoihalinh@gmail.com');
INSERT INTO `employee` VALUES ('123456', 'Mr Lợi Hồ', 'mrloiho97@gmail.com');
INSERT INTO `employee` VALUES ('123465', 'Loi Ho Sy', 'hosyloi97@gmail.com');
INSERT INTO `employee` VALUES ('13', 'Trần Thị Mèo Cat', 'tomtom@gmail.com');
INSERT INTO `employee` VALUES ('13232', 'Trần Văn Tài', 'taihoaso1@gmail.com');
INSERT INTO `employee` VALUES ('1323211', 'hihii', 'hihi@gmail.com');
INSERT INTO `employee` VALUES ('1323212', 'Mèo Thị Chó', 'meothicho@gmail');
INSERT INTO `employee` VALUES ('132322', 'Trần Văn Tâm', 'taihoaso1@gmail.com');
INSERT INTO `employee` VALUES ('13232222', 'Trần Văn Tôm', 'tomtom@gmail.com');
INSERT INTO `employee` VALUES ('132332', 'Trần Văn Tôm', 'tamtam@gmail.com');
